[package]
name = "dream"
version = "0.0.1"
authors = ["Radek Szymczyszyn <lavrin@gmail.com>"]

[lib]
name = "dream"
path = "src/dream/lib.rs"

[[bin]]
name = "idream"
path = "src/bin/idream.rs"

[dependencies]
docopt = "0.6.66"
rustc-serialize = "0.3.15"
